site_name: "CIDER: The Clojure Interactive Programming Environment that Rocks"
docs_dir: doc
pages:
- Home: index.md
- Installation: installation.md
- Basic Usage: basic_usage.md
- Using the REPL: using_the_repl.md
- Extended Workflow: extended_workflow.md
- Configuration: configuration.md
- Indentation Specification: indent_spec.md
- Additional Packages: additional_packages.md
- Caveats: caveats.md
- Troubleshooting: troubleshooting.md
- Support: support.md
- Additional Resources: additional_resources.md
- Team: team.md
- Release Policy: release_policy.md
- Logo: logo.md
- Contributing: contributing.md
- License: license.md
