site_name: "CIDER: The Clojure Interactive Programming Environment that Rocks"
repo_url: https://github.com/clojure-emacs/cider
site_favicon: favicon.ico
docs_dir: doc
pages:
- Home: index.md
- Installation: installation.md
- Up and Running: up_and_running.md
- Interactive Programming: interactive_programming.md
- Using the REPL: using_the_repl.md
- Code Completion: code_completion.md
- Running Tests: running_tests.md
- Debugging: debugging.md
- Extended Workflow: extended_workflow.md
- Configuration: configuration.md
- Indentation Specification: indent_spec.md
- Additional Packages: additional_packages.md
- Caveats: caveats.md
- Troubleshooting: troubleshooting.md
- Support: support.md
- Additional Resources: additional_resources.md
- Team: team.md
- Release Policy: release_policy.md
- Logo: logo.md
- Contributing: contributing.md
- License: license.md
extra_css:
  - css/extra.css
